### ISSUE TITLE
Some equivalent solutions not recognized

### ISSUE THREAD

**Issue by bryanclst** [tureptor/terraoptifind#3]
To reproduce, don't select any pylons, and unselect Santa Claus, Tax Collector, Demolitionist, and Tavernkeep (simplifies solutions). There is only 1 solution, but the Steampunker and Cyborg should have a setup where they're in the Desert. In the Snow, their values are 0.84/0.84. In the Desert (you can check this by upping Steampunker's weight), they would be 0.79/0.89, the average of which is equivalent.

Before rounding, Steampunker's 0.84 -> 0.79 decrease from being in the Desert is actually 0.0504, while Cyborg's 0.89 -> 0.84 decrease from being in the Snow is 0.0534. I'm guessing the calculator prioritizes the Cyborg here because of that.

**Comment by tureptor** [comment]
Great spot, a fix is out.
Your guess is close.
The calculator rounds the pricing modifier for each NPC before doing further calculations, so the decrease is correctly treated as 0.05 for both,
BUT, with JavaScript's floating point implementation, 0.79+0.84 is more(!) than 0.84+0.84 (as you can see below), so the desert biome is seen as worse. The fix is to round it to 8 decimal places after addition to get rid of that …0000002.
![image](https://user-images.githubusercontent.com/98993342/167537911-e401286b-57d8-4b05-8f43-6068f3af7dd3.png)
